name: nagarikbadapatra
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1 
  carousel_slider: ^5.1.1

  # ✅ Secure storage for token/password
  flutter_secure_storage: ^9.0.0

  # ✅ Biometrics (fingerprint/Face ID)
  local_auth: ^2.3.0

  # Audio/video
  audioplayers: ^6.2.0
  video_player: ^2.9.1
  flutter_tts: ^3.8.5
  youtube_player_flutter: ^9.1.3

  # Connectivity / networking
  connectivity_plus: ^6.1.0
  socket_io_client: ^2.0.3
  pusher_channels_flutter: 2.4.0
  restart_app: ^1.0.0
  url_launcher: ^6.3.1

  # UI / graphics
  marquee: ^2.2.3
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1

  # Database / storage
  sqflite: ^2.3.3
  sqlite3_flutter_libs: ^0.5.21
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sembast: ^3.8.0
  sembast_web: ^2.2.0
  drift: ^2.19.0

  # Webview
  webview_flutter: ^4.9.0

  # Flutter localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  drift_dev: ^2.19.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/flag.png
    - assets/mflag.jpg
    - assets/flag1.gif
    - assets/logonepal.jpg
    - assets/logo.jpg


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
